

GET http://localhost:8080/riders

###

POST http://localhost:8080/riders
Content-Type: application/json

{
    "name":"Rooster Road Captain",
    "city":"Las Vegas"
}

###

DELETE http://localhost:8080/riders/4

